### ISSUE TITLE
Using Perl 6 Grammars to parse?

### ISSUE THREAD

**Issue by trosel** [perl6/Pod-To-HTML#40]
Has anyone thought about using a Pod Grammar instead of this more imperative code? I think it could help a lot with maintainability.

**Comment by zoffixznet** [comment]
> Pod Grammar

I think in a Perfect World, the Pod-parsing portion of core grammar/actions (in Rakudo) would be a bit more separate. So if you're making your own `Pod::To::*` module, you'd just plug in your own Actions class and do what you gotta do. That'd be awesome.

Right now it's all intertwined with regular code parsing, because—really—Pod can be placed anywhere you can place whitespace, so if you're not parsing full Perl 6 code (including userland grammar mutations), it might be hard to extract just-pod from such a document.

**Comment by softmoth** [comment]
May be of interest: https://github.com/houseabsolute/perl6-Pod-TreeWalker

**Comment by WildYorkies** [comment]
Ah, so this is linked to the same code that is parsing Perl 6 itself. And Grammars don't exist until Perl 6 is parsed, so it's a chicken-egg situation.

**Comment by JJ** [comment]
And for that reason, I'm closing this issue since it does not actually depend on this module how Pod is parsed.
